# This workflow creates a release on a push to the main branch. 

name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  build:
    name: Create Build Release Artifact
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build Project
        run: dotnet build Source/Spectacle.sln
        
      - name: Zip Build Files
        uses: papeloto/action-zip@v1
        with:
          files: Source\bin\Debug\net5.0\
          dest: build_release.zip
        
      - name: Create Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_release
          path: build_release.zip
