# This workflow creates a release on a push to the main branch. 

name: CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  build:
    name: Create Build Release Artifact
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build Project
        run: dotnet build Source/Spectacle.sln
        
      - name: Zip Build Files
        uses: papeloto/action-zip@v1
        with:
          files: Source\bin\Debug\net5.0\
          dest: build_release.zip
        
      - name: Create Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build_release
          path: Source\bin\Debug\net5.0\

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build_release.zip
          asset_name: build_release.zip
          asset_content_type: application/zip
      
